// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/proto/events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	TsUnixNs      int64                  `protobuf:"varint,3,opt,name=ts_unix_ns,json=tsUnixNs,proto3" json:"ts_unix_ns,omitempty"`
	Stream        string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"` // "syslog" | "auth" | ...
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_internal_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *LogEvent) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *LogEvent) GetTsUnixNs() int64 {
	if x != nil {
		return x.TsUnixNs
	}
	return 0
}

func (x *LogEvent) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEvent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_proto_events_proto_rawDescGZIP(), []int{1}
}

var File_internal_proto_events_proto protoreflect.FileDescriptor

const file_internal_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/events.proto\x12\x05proto\"\xfa\x01\n" +
	"\bLogEvent\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1c\n" +
	"\n" +
	"ts_unix_ns\x18\x03 \x01(\x03R\btsUnixNs\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06stream\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x123\n" +
	"\x06labels\x18\x06 \x03(\v2\x1b.proto.LogEvent.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x05\n" +
	"\x03Ack2<\n" +
	"\vAgentIngest\x12-\n" +
	"\fStreamEvents\x12\x0f.proto.LogEvent\x1a\n" +
	".proto.Ack(\x01B9Z7github.com/mulutu/security-manager/internal/proto;protob\x06proto3"

var (
	file_internal_proto_events_proto_rawDescOnce sync.Once
	file_internal_proto_events_proto_rawDescData []byte
)

func file_internal_proto_events_proto_rawDescGZIP() []byte {
	file_internal_proto_events_proto_rawDescOnce.Do(func() {
		file_internal_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_events_proto_rawDesc), len(file_internal_proto_events_proto_rawDesc)))
	})
	return file_internal_proto_events_proto_rawDescData
}

var file_internal_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_events_proto_goTypes = []any{
	(*LogEvent)(nil), // 0: proto.LogEvent
	(*Ack)(nil),      // 1: proto.Ack
	nil,              // 2: proto.LogEvent.LabelsEntry
}
var file_internal_proto_events_proto_depIdxs = []int32{
	2, // 0: proto.LogEvent.labels:type_name -> proto.LogEvent.LabelsEntry
	0, // 1: proto.AgentIngest.StreamEvents:input_type -> proto.LogEvent
	1, // 2: proto.AgentIngest.StreamEvents:output_type -> proto.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_events_proto_init() }
func file_internal_proto_events_proto_init() {
	if File_internal_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_events_proto_rawDesc), len(file_internal_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_events_proto_goTypes,
		DependencyIndexes: file_internal_proto_events_proto_depIdxs,
		MessageInfos:      file_internal_proto_events_proto_msgTypes,
	}.Build()
	File_internal_proto_events_proto = out.File
	file_internal_proto_events_proto_goTypes = nil
	file_internal_proto_events_proto_depIdxs = nil
}
